# Generated by Django 5.0.7 on 2024-08-01 16:50

import django.db.models.deletion
import fall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_no', models.IntegerField(unique=True)),
                ('email_id', models.TextField(default=fall.models.email_default, verbose_name='Email ID')),
                ('caretaker_phone_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CT', 'Caretaker'), ('PA', 'Patient')], default='PA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_id', models.IntegerField(unique=True)),
                ('patient_phone_no', models.CharField(max_length=15, unique=True)),
                ('patient_email_id', models.TextField(default=fall.models.email_default, verbose_name='Email ID')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fall.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='FallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_time', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fall_histories', to='fall.patient')),
            ],
        ),
    ]
