# Generated by Django 5.0.7 on 2024-08-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='fall.caretaker'),
        ),
    ]
